FROM tensorflow/tensorflow:1.15.0-gpu-py3

RUN apt-get update && apt-get -y install git

COPY . /root/roam_rl

WORKDIR /root/roam_rl

RUN sed -e 's/sudo //g' -i setup.sh \
&& sed -i '/tensorflow/d' setup.sh \
&& bash setup.sh

CMD /bin/bash
